/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amy
 */
import java.io.*;
import java.util.*;
import javax.swing.table.*;

public class CustomQuestions extends javax.swing.JFrame {

    /**
     * Creates new form CustomQuestions
     */
    public CustomQuestions() {
        initComponents();
        updateTable();

    }
    
    public void updateTable() {
        DefaultTableModel tableModel = (DefaultTableModel)questionsTable.getModel();
        tableModel.setRowCount(0);
        //getting file
        try {
            Scanner readFile = new Scanner(new File(this.getClass().getResource("Questions.csv").getFile()));
            
            //reads through file
            int line = 0;
            while (readFile.hasNextLine()){
                //new scanner to read each lineNum
                Scanner readLine = new Scanner(readFile.nextLine());
                readLine.useDelimiter(",");
                
                //storing values of a lineNum
                String[] cells = new String[5];
                for (int i = 0; i < 5 && readLine.hasNext(); i++){
                    cells[i] = readLine.next(); 
                }
                tableModel.addRow(cells);
                line++;
            }
            readFile.close();
            questionsTable.setModel(tableModel);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtQuestion = new javax.swing.JTextField();
        lblQuestions = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        lblAnswers = new javax.swing.JLabel();
        lblOptions = new javax.swing.JLabel();
        txtOption1 = new javax.swing.JTextField();
        txtOption2 = new javax.swing.JTextField();
        txtOption3 = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        questionsTable = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        btnResetToDefault = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestions.setText("Question:");

        lblAnswers.setText("Answer:");

        lblOptions.setText("Multiple Choice Options:");

        lblTitle.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        lblTitle.setText("Create Your Own Questions");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBack.setText("Done");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        questionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question", "Answer", "Option 1", "Option 2", "Option 3"
            }
        ));
        jScrollPane2.setViewportView(questionsTable);
        if (questionsTable.getColumnModel().getColumnCount() > 0) {
            questionsTable.getColumnModel().getColumn(0).setPreferredWidth(250);
        }

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setText(" ");
        lblError.setToolTipText("");

        btnResetToDefault.setText("Reset to default");
        btnResetToDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetToDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitle)
                        .addGap(237, 237, 237))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblQuestions)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAnswers)
                                            .addGap(23, 23, 23)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                                        .addComponent(txtAnswer)))
                                .addComponent(txtOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnRemove)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblOptions))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBack)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnResetToDefault)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuestions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnswers))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOptions)
                    .addComponent(txtOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOption2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOption3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnRemove))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblError)
                            .addComponent(btnResetToDefault))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        lblError.setText("");
        
        //check are not empty
        if (!txtQuestion.getText().isEmpty() && !txtAnswer.getText().isEmpty()) {
            if (!txtOption1.getText().isEmpty() && !txtOption2.getText().isEmpty() && !txtOption3.getText().isEmpty()) {
                try {
                    FileWriter file = new FileWriter(new File(this.getClass().getResource("Questions.csv").getFile()), /*append*/true);

                    file.append(txtQuestion.getText() + "," + txtAnswer.getText() + "," + txtOption1.getText() + ","+ txtOption2.getText() + ","+ txtOption3.getText() + "\n");
                    file.close();

                    updateTable();  
                } catch (IOException e) {  
                    System.out.println("No Questions.csv file found");
                    e.printStackTrace();
                } 
            } else {
                lblError.setText("You are missing required information (Must have 3 options)");  
            }
        } else {
            lblError.setText("You are missing required information (Must include an answer and question)");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (questionsTable.getRowCount() == 0) {
            lblError.setText("You must have at least 1 question");
        } else {
            this.dispose();
            new MainMenu().setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel)questionsTable.getModel();
        
        lblError.setText("");
        //adding questions data to arrays
        ArrayList<String> updatedLines = new ArrayList<>(); 
        try{
            Scanner readFile = new Scanner(new File(this.getClass().getResource("Questions.csv").getFile()));

            int lineNum = 0;
            while (readFile.hasNextLine()){
                String line = readFile.nextLine();
                boolean shouldRemove = false;
                for (int removeLineNum : questionsTable.getSelectedRows()) {
                    if (removeLineNum == lineNum){
                        shouldRemove = true;
                        break;
                    }
                }
                if (!shouldRemove) {
                    updatedLines.add(line);
                }
                lineNum++;
            }
            readFile.close();
        } catch (IOException e) {
            System.out.println("No Questions.csv file found");
            e.printStackTrace();
        }
        
        try {
            FileWriter file = new FileWriter(new File(this.getClass().getResource("Questions.csv").getFile()));

            for (String line : updatedLines) {
                file.write(line + "\n");
            }
            file.close();

            updateTable();  
        } catch (IOException e) {  
            System.out.println("No Questions.csv file found");
            e.printStackTrace();
        } 
        
        updateTable();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnResetToDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetToDefaultActionPerformed
        
        lblError.setText("");
        try {
            FileWriter file = new FileWriter(new File(this.getClass().getResource("Questions.csv").getFile()));

            file.write("Donner (Futur): nous _____,donnerons,donnerai,donneront,donnerez\n"
                    + "Être (Présent): ils/elles _____,sont,êtes,est,étaient\n"
                    + "Faire (Imparfait): nous _____,faisions,faisais,faisait,faisons\n"
                    + "Pouvoir (Conditionnel Présent): tu _____,pourrais,pouvons,pouvez,pouvais\n"
                    + "Avoir (Présent): nous ____,avons,avez,a,avions\n"
                    + "Aller (Présent): vous ____,allez,allons,alliez,allais\n"
                    + "Dire (Conditionnel présent): tu _____,dirais,diraiz,dirions,diraient\n"
                    + "Savoir (Futur Antérieur): nous _____,aurons su,ai su,aurai su,auras su");
            file.close();

            updateTable();  
        } catch (IOException e) {  
            System.out.println("No Questions.csv file found");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnResetToDefaultActionPerformed

    /**
     * @param args the command lineNum arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomQuestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnResetToDefault;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnswers;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblOptions;
    private javax.swing.JLabel lblQuestions;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable questionsTable;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtOption1;
    private javax.swing.JTextField txtOption2;
    private javax.swing.JTextField txtOption3;
    private javax.swing.JTextField txtQuestion;
    // End of variables declaration//GEN-END:variables
}
