/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Amy Zhang
 * Date: October 16, 2023
 * 
 */
import java.util.*;
        
public class CustomMethods extends javax.swing.JFrame {

    boolean easyMode = false, questionMode = false;
    int userHealth = 100, compHealth = 100, questionIndex;
    String userGuess;
    // 10 questions default
    String[] questions = new String[10];
    String[][] answers = new String[10][5]; //answer and then 4 options
    //String[][] options = {{"avoir", "avior", "avror", "aee"},{"être"}, {"devoir"}, {"pouvoir"}};
   // String[] questions = {""}, answers = {"avoir"};
    
    /**
     * Creates new form CustomMethods
     */
    public CustomMethods() {
        initComponents();
        
        //nothing except textarea is visible
        btnSkip.setVisible(false);
        btnHint.setVisible(false);
        btnSubmit.setVisible(false);
        txtGuess.setVisible(false);
        comboOptions.setVisible(false);
        questionMode = true;
    }
    
    public static int damage (int bound){
        Random rand = new Random();
        int damage = rand.nextInt(0, bound);
        
        if (damage == 0) {
            //say it missed
            return 0;
        }
        if (damage == bound - 1){
            //say critical hit
            return bound + 3;
        }
        return damage;
    }
    
    public void updateHealth(){
        compHealthBar.setValue(compHealth);
        userHealthBar.setValue(userHealth);
    }
    
    public void changeQMode(){
        if (questionMode){
            btnArrow.setVisible(false);
            btnSubmit.setVisible(true);
            
            btnSkip.setVisible(true);
            btnHint.setVisible(true);
            txtGuess.setVisible(true);
            comboOptions.setVisible(false);
            
            questionMode = false;
            
        } else { //showing answer and damage
            btnArrow.setVisible(true);
            btnSubmit.setVisible(false);
            
            btnHint.setVisible(false);
            btnHint.setSelected(false);
            btnHint.setEnabled(true);
            easyMode = false;
            
            btnSkip.setVisible(false);
            txtGuess.setVisible(false);
            comboOptions.setVisible(false);
            
            questionMode = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jSlider1 = new javax.swing.JSlider();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        userHealthBar = new javax.swing.JProgressBar();
        btnArrow = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        compHealthBar = new javax.swing.JProgressBar();
        comboOptions = new javax.swing.JComboBox<>();
        btnSkip = new javax.swing.JButton();
        txtGuess = new javax.swing.JTextField();
        btnHint = new javax.swing.JToggleButton();
        lblCompImage = new javax.swing.JLabel();
        lblUserImage = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userHealthBar.setForeground(new java.awt.Color(0, 204, 0));
        userHealthBar.setValue(100);

        btnArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow.png"))); // NOI18N
        btnArrow.setBorderPainted(false);
        btnArrow.setIconTextGap(0);
        btnArrow.setPreferredSize(new java.awt.Dimension(40, 50));
        btnArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrowActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitle.setText("Battle");

        txtOutput.setEditable(false);
        txtOutput.setColumns(20);
        txtOutput.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtOutput.setLineWrap(true);
        txtOutput.setRows(5);
        txtOutput.setText("Welcome...\nClick the arrow button to continue");
        jScrollPane3.setViewportView(txtOutput);

        compHealthBar.setForeground(new java.awt.Color(0, 204, 0));
        compHealthBar.setValue(100);

        comboOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSkip.setText("Don't know");
        btnSkip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkipActionPerformed(evt);
            }
        });

        btnHint.setText("Hint");
        btnHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHintActionPerformed(evt);
            }
        });

        lblCompImage.setText("jLabel1");

        lblUserImage.setText("jLabel2");

        btnSubmit.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorderPainted(false);
        btnSubmit.setIconTextGap(0);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(compHealthBar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(userHealthBar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHint)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSkip)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSubmit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnArrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane3))))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCompImage)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblUserImage)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(26, 26, 26)
                .addComponent(compHealthBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lblUserImage)
                .addGap(17, 17, 17)
                .addComponent(lblCompImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(userHealthBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSubmit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSkip)
                    .addComponent(btnHint))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrowActionPerformed
        Random rand = new Random();
        boolean isEnd = false;
        
        if (compHealth <= 0 || userHealth <= 0) {
            //final screen, show winner, change image
            txtOutput.setText("Congrats! You have defeated the ++ with ++ health left"
                    + "Click the arrow button to return to the menu");
            //lblUserImage.setIcon("userVictory.png");

            //If second time pressed
            if (isEnd == true){
                this.dispose();
                new FrmMenu().setVisible(true);
            }
            isEnd = true;
            
        } else {
            questionIndex = rand.nextInt(0, 10);
            //display next question
            txtOutput.setText(questions[questionIndex]);
            changeQMode();
        }
    }//GEN-LAST:event_btnArrowActionPerformed

    private void btnSkipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkipActionPerformed
        if (easyMode) {
            userHealth -= damage(7);
        } else {
            userHealth -= damage(12);
        }
        //show answer
        
        updateHealth();
        changeQMode();
    }//GEN-LAST:event_btnSkipActionPerformed

    private void btnHintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHintActionPerformed
        if (btnHint.isSelected()){         
            //switch to easy mode
            comboOptions.setVisible(true);
            txtGuess.setVisible(false);
            btnHint.setEnabled(false);
            easyMode = true;   
            
            //change options
            comboOptions.removeAllItems();
            for (String[] question : answers) {
                comboOptions.addItem("item");
            }
        } 
    }//GEN-LAST:event_btnHintActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
            //check which mode (easy/normal)
            if (easyMode){
                userGuess = String.valueOf(comboOptions.getSelectedItem());
                // try except if nothing is selected
            } else {
                userGuess = String.valueOf(txtGuess);
            }

            //dealing damage
            if (userGuess.equals(answers[questionIndex])){
                if (easyMode){
                    compHealth -= damage(7);
                } else {
                    compHealth -= damage(7);
                }
            } else {
                if (easyMode){
                    userHealth -= damage(12);
                } else {
                    userHealth -= damage(12); 
                }
            }
            
            updateHealth();
            changeQMode();
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArrow;
    private javax.swing.JToggleButton btnHint;
    private javax.swing.JButton btnSkip;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> comboOptions;
    private javax.swing.JProgressBar compHealthBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblCompImage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserImage;
    private javax.swing.JTextField txtGuess;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JProgressBar userHealthBar;
    // End of variables declaration//GEN-END:variables
}
